openapi: 3.0.3
info:
  title: Onboarding API 1.2
  description: |-
    STD22048 
    RAKOTONIAINA Joro Sullivan
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: hei.sullivan.2@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://STD22048
tags:
  - name: Student
    description: Everything about your Students
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /Student:
    get:
      tags:
        - Student
      summary: Update an existing student
      description: Update an existing student by Id
      operationId: updateStudent
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Student'
    post:
      tags:
        - Student
      summary: Add a new student to the school
      description: Add a new student to the school
      operationId: addStudent
      requestBody:
        description: Create a new student in the school
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/xml:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Student'
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:students
            - read:students
    put:
      tags:
        - Student
      summary: Update student by ID (Full Update)
      description: Update student by ID (Full Update)
      operationId: updateStudentById
      parameters:
        - name: studentId
          in: path
          description: ID of student to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Updated student object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    delete:
      tags:
        - Student
      summary: Delete student by ID
      description: Delete student by ID
      operationId: deleteStudentById
      parameters:
        - name: studentId
          in: path
          description: ID of student to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
      security:
        - api_key: []
        - petstore_auth:
            - write:students
            - read:students
components:
  schemas:
    Address:
      type: object
      properties:
        quarter:
          type: string
          example: Ankirihiry Nord
        city:
          type: string
          example: Tamatave
        region:
          type: string
          example: Antsinanana
        lot:
          type: string
          example: '0284'
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        class:
          type: string
          example: H2 - L1
      xml:
        name: category
    Student:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: sullivan
        STD:
          type: integer
          format: int64
          example: 22048
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        status:
          type: string
          description: student status in the school
          enum:
            - left
            - active
            - finished
      xml:
        name: student
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Student:
      description: Object student who would like to be researched at school
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Search'
        application/xml:
          schema:
            $ref: '#/components/schemas/Search'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://student.swagger.io/oauth/authorize
          scopes:
            write:students: modify student in your school
            read:students: read your students
    api_key:
      type: apiKey
      name: api_key
      in: header
